### ISSUE TITLE
Can I use this in production environment?

### ISSUE THREAD

**Issue by raku** [N3Cr0N/HMVC#8]
Hello,

Can I use this in production environment? When you will do an release?

Thanks.

**Comment by N3Cr0N** [comment]
Hello,
yes you can use it in production environment.

i hope to find people with this project to extension the original project and work from wiredesignz, they have no code added since 2015 in this own project.

i have make little fixes in the code and bring PHP PSR 1-2 standards in code,
i make little fixes to run this code at different php versions, regarding outdated php function in version 7.

If you want the original code you can find in my project under the branch "untouched" or you use the original code from the original developer from here https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc

Also you can use this project from me, i have added this HMVC project to Codeigniter 3.1.10 https://github.com/N3Cr0N/CodeIgniter-HMVC

Kind regards

**Comment by raku** [comment]
What issues do you want to resolve until release it?

**Comment by N3Cr0N** [comment]
It is released, i have found no bugs at the moment in the "master" and "php-backward" branch, i hope more people make a look at the code, and checked the code or/and found bugs or/and extended the code.

The "Support-Namespaces" branch is a copy of a commit at bitbucket, at the moment i have not the time to checked this code function.
